"""Constants for the Roadplanner integration."""

from __future__ import annotations

DOMAIN = "roadplanner_mcp"
NAME = "Roadplanner"
INTEGRATION_VERSION = "3.4.0"

LLM_API_ID = "roadplanner"
LLM_API_NAME = "Roadplanner"

CONFIG_ENTRY_VERSION = 12

EVENT_ROADPLANNER_UPDATED = "roadplanner_mcp_updated"
EVENT_HANDOFF_RECEIVED = f"{DOMAIN}_handoff_received"
EVENT_HANDOFF_APPLIED = f"{DOMAIN}_handoff_applied"
EVENT_HANDOFF_CONFLICT = f"{DOMAIN}_handoff_conflict"

DRIVE_IMPORT_PATH = "/api/roadplanner/drive-import"
DRIVE_IMPORT_SECRET_HEADER = "X-Roadplanner-Secret"

CONF_ROADBOOK_PATH = "roadbook_path"
CONF_BACKUP_PATH = "backup_path"
CONF_HANDOFF_PATH = "handoff_path"
CONF_BACKUP_COUNT = "backup_count"
CONF_REFRESH_INTERVAL = "refresh_interval"
CONF_ENABLE_HANDOFF_WEBHOOK = "enable_handoff_webhook"
CONF_AUTO_SCAN_HANDOFFS = "auto_scan_handoffs"
CONF_AUTO_APPLY_CHANGESETS = "auto_apply_changesets"
CONF_ALLOW_DESTRUCTIVE_AUTO_APPLY = "allow_destructive_auto_apply"
CONF_NON_ADMIN_ROLE = "non_admin_role"
CONF_WEBHOOK_ID = "handoff_webhook_id"
CONF_WEBHOOK_TOKEN = "handoff_webhook_token"
CONF_INITIALIZED_PATH = "initialized_path"

CONF_ASSISTANT_PROVIDER = "assistant_provider"
CONF_GEMINI_API_KEY = "gemini_api_key"
CONF_GEMINI_MODEL = "gemini_model"
CONF_GEMINI_FALLBACK_MODEL = "gemini_fallback_model"
CONF_ASSISTANT_REQUEST_TIMEOUT = "assistant_request_timeout"
CONF_ASSISTANT_RETRY_ATTEMPTS = "assistant_retry_attempts"
CONF_ASSISTANT_MIN_REQUEST_INTERVAL = "assistant_min_request_interval"
CONF_ASSISTANT_MAX_QUEUE = "assistant_max_queue"
CONF_ASSISTANT_AUTONOMY_LEVEL = "assistant_autonomy_level"
CONF_ASSISTANT_COPILOT_ENABLED = "assistant_copilot_enabled"
CONF_ASSISTANT_COPILOT_AUTO_BRIEFING = "assistant_copilot_auto_briefing"
CONF_ASSISTANT_DEBUG_ENABLED = "assistant_debug_enabled"
CONF_ASSISTANT_ENABLE_RESEARCH = "assistant_enable_research"
CONF_ASSISTANT_MAX_HISTORY = "assistant_max_history"
CONF_GEOCODING_ENABLED = "geocoding_enabled"
CONF_GEOCODING_URL = "geocoding_url"

CONF_ROUTING_ENABLED = "routing_enabled"
CONF_ROUTING_PROVIDER = "routing_provider"
CONF_ROUTING_URL = "routing_url"
CONF_ROUTING_PROFILE = "routing_profile"
CONF_ROUTING_REQUEST_TIMEOUT = "routing_request_timeout"
CONF_ROUTING_MIN_REQUEST_INTERVAL = "routing_min_request_interval"
CONF_ARCHIVE_PATH = "archive_path"
CONF_DOCUMENT_MAX_UPLOAD_MB = "document_max_upload_mb"
CONF_DOCUMENT_ANALYSIS_ENABLED = "document_analysis_enabled"
CONF_DEFAULT_CURRENCY = "default_currency"

CONF_ONEDRIVE_ENABLED = "onedrive_enabled"
CONF_ONEDRIVE_CLIENT_ID = "onedrive_client_id"
CONF_ONEDRIVE_PHOTO_FOLDER = "onedrive_photo_folder"
CONF_ONEDRIVE_AUTO_SYNC = "onedrive_auto_sync"
CONF_ONEDRIVE_SYNC_INTERVAL = "onedrive_sync_interval"
CONF_ONEDRIVE_AUTO_ASSIGN = "onedrive_auto_assign"
CONF_ONEDRIVE_RECURSIVE = "onedrive_recursive"
CONF_ONEDRIVE_DATE_BUFFER_DAYS = "onedrive_date_buffer_days"
CONF_ONEDRIVE_MAX_ITEMS_PER_RUN = "onedrive_max_items_per_run"
CONF_ONEDRIVE_MAX_SCAN_SECONDS = "onedrive_max_scan_seconds"

CONF_MEDIA_CURATION_MODE = "media_curation_mode"
CONF_MEDIA_VISION_MAX_CANDIDATES = "media_vision_max_candidates"
CONF_MEDIA_VISION_MAX_HIGHLIGHTS = "media_vision_max_highlights"
CONF_MEDIA_VISION_DAILY_LIMIT = "media_vision_daily_limit"

# Legacy option retained only for config-entry migration from 1.1.0.
CONF_STORAGE_PATH = "storage_path"

ROLE_VIEWER = "viewer"
ROLE_EDITOR = "editor"
ROLE_APPROVER = "approver"
ROLE_ADMIN = "admin"
NON_ADMIN_ROLES = (ROLE_VIEWER, ROLE_EDITOR, ROLE_APPROVER)

DEFAULT_ROADBOOK_PATH = "www/roadbook"
DEFAULT_BACKUP_PATH = ".roadplanner_backups"
DEFAULT_HANDOFF_PATH = ".roadplanner_handoffs"
DEFAULT_BACKUP_COUNT = 20
DEFAULT_REFRESH_INTERVAL = 60
DEFAULT_ENABLE_HANDOFF_WEBHOOK = False
DEFAULT_AUTO_SCAN_HANDOFFS = True
DEFAULT_AUTO_APPLY_CHANGESETS = False
DEFAULT_ALLOW_DESTRUCTIVE_AUTO_APPLY = False
DEFAULT_NON_ADMIN_ROLE = ROLE_VIEWER

DEFAULT_ASSISTANT_PROVIDER = "gemini"
DEFAULT_GEMINI_API_KEY = ""
DEFAULT_GEMINI_MODEL = "gemini-3.5-flash"
DEFAULT_GEMINI_FALLBACK_MODEL = "gemini-2.5-flash"
DEFAULT_ASSISTANT_REQUEST_TIMEOUT = 75
DEFAULT_ASSISTANT_RETRY_ATTEMPTS = 2
DEFAULT_ASSISTANT_MIN_REQUEST_INTERVAL = 2.0
DEFAULT_ASSISTANT_MAX_QUEUE = 8
ASSISTANT_AUTONOMY_LEVELS = ("answers", "suggestions", "change_basket")
DEFAULT_ASSISTANT_AUTONOMY_LEVEL = "change_basket"
DEFAULT_ASSISTANT_COPILOT_ENABLED = True
DEFAULT_ASSISTANT_COPILOT_AUTO_BRIEFING = False
DEFAULT_ASSISTANT_DEBUG_ENABLED = False
DEFAULT_ASSISTANT_ENABLE_RESEARCH = True
DEFAULT_ASSISTANT_MAX_HISTORY = 24
DEFAULT_GEOCODING_ENABLED = True
DEFAULT_GEOCODING_URL = "https://nominatim.openstreetmap.org/search"
DEFAULT_ROUTING_ENABLED = False
DEFAULT_ROUTING_PROVIDER = "osrm"
DEFAULT_ROUTING_URL = "https://router.project-osrm.org"
DEFAULT_ROUTING_PROFILE = "driving"
DEFAULT_ROUTING_REQUEST_TIMEOUT = 45
DEFAULT_ROUTING_MIN_REQUEST_INTERVAL = 1.1
DEFAULT_ARCHIVE_PATH = ".roadplanner_archive"
DEFAULT_DOCUMENT_MAX_UPLOAD_MB = 25
DEFAULT_DOCUMENT_ANALYSIS_ENABLED = True
DEFAULT_DEFAULT_CURRENCY = "EUR"

DEFAULT_ONEDRIVE_ENABLED = False
DEFAULT_ONEDRIVE_CLIENT_ID = ""
DEFAULT_ONEDRIVE_PHOTO_FOLDER = "Pictures/Camera Roll"
DEFAULT_ONEDRIVE_AUTO_SYNC = True
DEFAULT_ONEDRIVE_SYNC_INTERVAL = 15
DEFAULT_ONEDRIVE_AUTO_ASSIGN = True
DEFAULT_ONEDRIVE_RECURSIVE = True
DEFAULT_ONEDRIVE_DATE_BUFFER_DAYS = 3
DEFAULT_ONEDRIVE_MAX_ITEMS_PER_RUN = 2000
DEFAULT_ONEDRIVE_MAX_SCAN_SECONDS = 12
MIN_ONEDRIVE_SYNC_INTERVAL = 5
MAX_ONEDRIVE_SYNC_INTERVAL = 1440
MIN_ONEDRIVE_DATE_BUFFER_DAYS = 0
MAX_ONEDRIVE_DATE_BUFFER_DAYS = 30
MIN_ONEDRIVE_MAX_ITEMS_PER_RUN = 100
MAX_ONEDRIVE_MAX_ITEMS_PER_RUN = 5000
MIN_ONEDRIVE_MAX_SCAN_SECONDS = 3
MAX_ONEDRIVE_MAX_SCAN_SECONDS = 60

MEDIA_CURATION_MODES = ("local", "hybrid")
DEFAULT_MEDIA_CURATION_MODE = "local"
DEFAULT_MEDIA_VISION_MAX_CANDIDATES = 12
DEFAULT_MEDIA_VISION_MAX_HIGHLIGHTS = 5
DEFAULT_MEDIA_VISION_DAILY_LIMIT = 5
MIN_MEDIA_VISION_MAX_CANDIDATES = 3
MAX_MEDIA_VISION_MAX_CANDIDATES = 15
MIN_MEDIA_VISION_MAX_HIGHLIGHTS = 1
MAX_MEDIA_VISION_MAX_HIGHLIGHTS = 8
MIN_MEDIA_VISION_DAILY_LIMIT = 0
MAX_MEDIA_VISION_DAILY_LIMIT = 100
MIN_DOCUMENT_MAX_UPLOAD_MB = 1
MAX_DOCUMENT_MAX_UPLOAD_MB = 100
MIN_ROUTING_REQUEST_TIMEOUT = 10
MAX_ROUTING_REQUEST_TIMEOUT = 180
MIN_ROUTING_MIN_REQUEST_INTERVAL = 0.2
MAX_ROUTING_MIN_REQUEST_INTERVAL = 30.0
MIN_ASSISTANT_MAX_HISTORY = 8
MAX_ASSISTANT_MAX_HISTORY = 80
MIN_ASSISTANT_REQUEST_TIMEOUT = 20
MAX_ASSISTANT_REQUEST_TIMEOUT = 180
MIN_ASSISTANT_RETRY_ATTEMPTS = 0
MAX_ASSISTANT_RETRY_ATTEMPTS = 5
MIN_ASSISTANT_MIN_REQUEST_INTERVAL = 0.5
MAX_ASSISTANT_MIN_REQUEST_INTERVAL = 15.0
MIN_ASSISTANT_MAX_QUEUE = 1
MAX_ASSISTANT_MAX_QUEUE = 50
MIN_REFRESH_INTERVAL = 15
MAX_REFRESH_INTERVAL = 3600

# JSON transport envelope; ChangeSet content itself remains limited to 512 KiB.
MAX_WEBHOOK_BYTES = 1024 * 1024
MAX_DRIVE_IMPORT_BYTES = 256 * 1024
DRIVE_IMPORT_RATE_LIMIT_REQUESTS = 30
DRIVE_IMPORT_RATE_LIMIT_WINDOW_SECONDS = 5 * 60

SERVICE_GET_TRIP_SUMMARY = "get_trip_summary"
SERVICE_GET_DAYS = "get_days"
SERVICE_GET_DAY = "get_day"
SERVICE_SEARCH_STOPS = "search_stops"
SERVICE_LIST_TRIPS = "list_trips"
SERVICE_SET_ACTIVE_TRIP = "set_active_trip"
SERVICE_UPDATE_TRIP = "update_trip"
SERVICE_ADD_DAY = "add_day"
SERVICE_UPDATE_DAY = "update_day"
SERVICE_REMOVE_DAY = "remove_day"
SERVICE_ADD_STOP = "add_stop"
SERVICE_UPDATE_STOP = "update_stop"
SERVICE_REMOVE_STOP = "remove_stop"
SERVICE_EXPORT_TRIP = "export_trip"
SERVICE_CREATE_BACKUP = "create_backup"
SERVICE_ADOPT_EXTERNAL_CHANGES = "adopt_external_changes"
SERVICE_RELOAD = "reload"
SERVICE_LIST_HANDOFFS = "list_handoffs"
SERVICE_GET_HANDOFF = "get_handoff"
SERVICE_INGEST_HANDOFF = "ingest_handoff"
SERVICE_INGEST_CHANGESET = "ingest_changeset"
SERVICE_PREVIEW_HANDOFF = "preview_handoff"
SERVICE_APPLY_HANDOFF = "apply_handoff"
SERVICE_ARCHIVE_HANDOFF = "archive_handoff"
SERVICE_SCAN_HANDOFFS = "scan_handoffs"
SERVICE_GET_HANDOFF_FOLDERS = "get_handoff_folders"
SERVICE_GET_HANDOFF_ENDPOINT = "get_handoff_endpoint"
SERVICE_ROTATE_HANDOFF_SECRET = "rotate_handoff_secret"
SERVICE_EXPORT_CONTEXT = "export_context"
SERVICE_CALCULATE_DAY_ROUTE = "calculate_day_route"
SERVICE_CALCULATE_TRIP_ROUTES = "calculate_trip_routes"
SERVICE_CREATE_EXPENSE = "create_expense"
SERVICE_CREATE_TODO = "create_todo"

ATTR_EXPECTED_REVISION = "expected_revision"
