export const WS_GET_DATA = "roadplanner_mcp/panel/get_data";
export const WS_ACTION = "roadplanner_mcp/panel/action";

export const operationLabels = {
  update_trip: "Reise ändern",
  add_day: "Tag hinzufügen",
  update_day: "Tag ändern",
  move_day: "Tag verschieben",
  remove_day: "Tag löschen",
  add_stop: "Stopp hinzufügen",
  update_stop: "Stopp ändern",
  move_stop: "Stopp verschieben",
  remove_stop: "Stopp löschen",
  add_preference: "Präferenz hinzufügen",
  update_preference: "Präferenz ändern",
  remove_preference: "Präferenz löschen",
};

export const statusLabels = {
  planned: "Geplant",
  tentative: "Vorläufig",
  confirmed: "Bestätigt",
  completed: "Erledigt",
  cancelled: "Entfällt",
  pending: "Offen",
  review_required: "Prüfung nötig",
  conflict: "Konflikt",
  failed: "Fehler",
  applied: "Übernommen",
  archived: "Archiviert",
  waypoint: "Wegpunkt",
  start: "Start",
  origin: "Start",
  destination: "Tagesziel",
  overnight: "Übernachtung",
  ferry: "Fähre",
  campsite: "Campingplatz",
  camping: "Stellplatz",
  parking: "Parkplatz",
  sightseeing: "Stadtbesichtigung",
  attraction: "Sehenswürdigkeit",
  activity: "Aktivität",
  restaurant: "Restaurant",
  shopping: "Einkauf",
  charging: "Ladepunkt",
  fuel: "Tankstelle",
  service: "Service",
  water: "Wasser",
  waste: "Entsorgung",
  laundry: "Wäsche",
  border: "Grenze",
  break: "Pause",
  viewpoint: "Aussichtspunkt",
  fishing: "Angelplatz",
  viewer: "Leser",
  editor: "Bearbeiter",
  approver: "Freigeber",
  admin: "Administrator",
};

export const archiveDocumentTypeLabels = {
  ferry_booking: "Fährbuchung",
  camping_booking: "Campingplatzbuchung",
  accommodation_booking: "Unterkunft",
  restaurant_reservation: "Restaurantreservierung",
  event_ticket: "Veranstaltungsticket",
  admission_ticket: "Eintrittsticket",
  transport_ticket: "Transportticket",
  invoice: "Rechnung",
  receipt: "Beleg",
  insurance: "Versicherung",
  vehicle_document: "Fahrzeugdokument",
  fishing_license: "Angellizenz",
  travel_document: "Reisedokument",
  other: "Sonstiges",
};

export const archiveExpenseCategoryLabels = {
  fuel: "Tanken",
  charging: "Laden",
  campsite: "Campingplatz",
  motorhome_site: "Stellplatz",
  parking: "Parken",
  restaurant: "Restaurant",
  snack: "Imbiss",
  groceries: "Lebensmittel",
  ferry: "Fähre",
  transport: "Transportmittel",
  other: "Sonstiges",
};

export const archiveStatusLabels = {
  draft: "Neu", analysis_pending: "Analyse läuft", analyzed: "Analysiert",
  confirmed: "Bestätigt", cancelled: "Storniert", expired: "Abgelaufen",
  file_removed: "Original gelöscht", open: "Offen", done: "Erledigt",
  dismissed: "Verworfen", planned: "Geplant", paid: "Bezahlt",
  refundable: "Erstattbar", refunded: "Erstattet", unknown: "Unklar",
};

export const stopIcons = {
  waypoint: "mdi:map-marker-outline",
  start: "mdi:flag-outline",
  origin: "mdi:flag-outline",
  destination: "mdi:flag-checkered",
  overnight: "mdi:weather-night",
  ferry: "mdi:ferry",
  campsite: "mdi:tent",
  camping: "mdi:van-utility",
  parking: "mdi:parking",
  sightseeing: "mdi:city-variant-outline",
  attraction: "mdi:camera-marker-outline",
  activity: "mdi:hiking",
  restaurant: "mdi:silverware-fork-knife",
  shopping: "mdi:cart-outline",
  charging: "mdi:ev-station",
  fuel: "mdi:gas-station-outline",
  service: "mdi:tools",
  water: "mdi:water-outline",
  waste: "mdi:delete-outline",
  laundry: "mdi:washing-machine",
  border: "mdi:passport",
  break: "mdi:coffee-outline",
  viewpoint: "mdi:binoculars",
  fishing: "mdi:fish",
};
